language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
  - julia -e 'Pkg.clone(pwd()); Pkg.build("RouletteWheels")'
  - julia -e 'Pkg.test("RouletteWheels"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("RouletteWheels")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'